Repository jenkinsci/label-verifier-plugin, pull requests merged in 2024-06, with the labels that each got.

#16 Updated parent POM to 4.76
  pom.xml
Labels: chore

#18 Require Jenkins 2.426.3 and latest parent pom
  Jenkinsfile
  pom.xml
Labels: chore

#19 Format with spotless
  README.md
  pom.xml
  src/main/java/hudson/plugins/label_verifier/ComputerListenerImpl.java
  src/main/java/hudson/plugins/label_verifier/LabelAtomPropertyImpl.java
  src/main/java/hudson/plugins/label_verifier/LabelVerifier.java
  src/main/java/hudson/plugins/label_verifier/LabelVerifierDescriptor.java
  src/main/java/hudson/plugins/label_verifier/logic/AlwaysFalse.java
  src/main/java/hudson/plugins/label_verifier/logic/AlwaysTrue.java
  src/main/java/hudson/plugins/label_verifier/logic/And.java
  src/main/java/hudson/plugins/label_verifier/logic/LogicHelper.java
  src/main/java/hudson/plugins/label_verifier/logic/Not.java
  src/main/java/hudson/plugins/label_verifier/logic/Or.java
  src/main/java/hudson/plugins/label_verifier/util/LabelVerifierException.java
  src/main/java/hudson/plugins/label_verifier/verifiers/RegexNameVerifier.java
  src/main/java/hudson/plugins/label_verifier/verifiers/ShellScriptVerifier.java
  src/test/java/hudson/plugins/label_verifier/LabelVerifierTest.java
  src/test/java/hudson/plugins/label_verifier/LabelVerifierTestCase.java
  src/test/java/hudson/plugins/label_verifier/verifiers/LogicTest.java
  src/test/java/hudson/plugins/label_verifier/verifiers/RegexNameVerifierTest.java
Labels: chore

#20 Incrementalify
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: chore

#21 Add spotbugs checks
  pom.xml
Labels: chore

#22 Automate dependency updates
  .github/dependabot.yml
Labels: chore

#23 Add CODEOWNERS configuration
  .github/CODEOWNERS
Labels: chore

#26 Document a configuration as code sample
  README.md
Labels: documentation

#27 Fix errors in online help
  src/main/resources/hudson/plugins/label_verifier/LabelAtomPropertyImpl/help.html
  src/main/resources/hudson/plugins/label_verifier/verifiers/RegexNameVerifier/help-regexExpression.html
  src/main/resources/hudson/plugins/label_verifier/verifiers/ShellScriptVerifier/help-script.html
Labels: documentation

#25 Enable automated plugin release (CD) on relevant changes
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: developer
